export const constants = {
    GETTING_MERCURY_DATA: 'GETTING_MERCURY_DATA',
    GOT_MERCURY_DATA: 'GOT_MERCURY_DATA', 
    USER_LOGIN:'USER_LOGIN',
    PAGE_HITS: 'PAGE_HITS',
    GET_POCKET_DEVELOPER: 'GET_POCKET_DEVELOPER',
    GOT_POCKET_DATA: 'GOT_POCKET_DATA',
    SET_POCKET: 'SET_POCKET'
}
// export const GET_POCKET_DEVELOPER = 'GET_POCKET_DEVELOPER'

export default constants;
